blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/brennercruvinel/prettyeyes/discussions
    about: Ask questions and discuss with other community members
  - name: Security Issues
    url: https://github.com/brennercruvinel/prettyeyes/security/advisories
    about: Please report security vulnerabilities here